name: angel_dress_acheteur
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.0
  convex_bottom_bar: ^2.6.0
  firebase_core: ^0.5.0
  firebase_auth: "^0.18.0+1"
  #firebase_crashlytics: "^0.2.4"
  cloud_firestore: "^0.14.0+2"
  cloud_functions: "^0.7.2"
  firebase_storage: "^5.2.0"
  firebase_messaging: "^7.0.3"
  firebase_remote_config: "^0.4.3"
  # Updated to work with new core only plugins (no new changes):
  #firebase_admob: "^"
  firebase_analytics: "^6.3.0"
  firebase_database: "^4.4.0"
  firebase_dynamic_links: "^0.6.3"
  #firebase_in_app_messaging: "^0.2.3"
  firebase_performance: "^0.4.3"
  #firebase_analytics: ^6.3.0
  #firebase_app_check: "^N/A"
  #cloud_firestore: ^0.13.7
  #firebase_database: ^3.1.6
  #firebase_auth: ^0.16.1
  firebase: ^7.3.0
  font_awesome_flutter: ^8.11.0
  #flappy_search_bar: ^1.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
